#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui/capturewidget.ui on Sat Apr  9 14:27:42 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_VideoWidget(object):
    def setupUi(self, VideoWidget):
        VideoWidget.setObjectName(_fromUtf8("VideoWidget"))
        VideoWidget.resize(448, 463)
        VideoWidget.setWindowTitle(_fromUtf8(""))
        self.verticalLayout_2 = QtGui.QVBoxLayout(VideoWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.videoFrame = QtGui.QFrame(VideoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoFrame.sizePolicy().hasHeightForWidth())
        self.videoFrame.setSizePolicy(sizePolicy)
        self.videoFrame.setMinimumSize(QtCore.QSize(440, 330))
        self.videoFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.videoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.videoFrame.setObjectName(_fromUtf8("videoFrame"))
        self.verticalLayout_2.addWidget(self.videoFrame)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.sourceLabel = QtGui.QLabel(VideoWidget)
        self.sourceLabel.setObjectName(_fromUtf8("sourceLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sourceLabel)
        self.sourceRequester = KUrlRequester(VideoWidget)
        self.sourceRequester.setObjectName(_fromUtf8("sourceRequester"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sourceRequester)
        self.capsLabel = QtGui.QLabel(VideoWidget)
        self.capsLabel.setObjectName(_fromUtf8("capsLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.capsLabel)
        self.capsInput = KIntNumInput(VideoWidget)
        self.capsInput.setObjectName(_fromUtf8("capsInput"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.capsInput)
        self.desintationLabel = QtGui.QLabel(VideoWidget)
        self.desintationLabel.setObjectName(_fromUtf8("desintationLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.desintationLabel)
        self.destinationRequester = KUrlRequester(VideoWidget)
        self.destinationRequester.setObjectName(_fromUtf8("destinationRequester"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.destinationRequester)
        self.verticalLayout.addLayout(self.formLayout)
        self.captureButton = KPushButton(VideoWidget)
        self.captureButton.setObjectName(_fromUtf8("captureButton"))
        self.verticalLayout.addWidget(self.captureButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(VideoWidget)
        QtCore.QMetaObject.connectSlotsByName(VideoWidget)

    def retranslateUi(self, VideoWidget):
        self.sourceLabel.setText(kdecore.i18n(_fromUtf8("Source file")))
        self.capsLabel.setText(kdecore.i18n(_fromUtf8("Number of screencaps")))
        self.desintationLabel.setText(kdecore.i18n(_fromUtf8("Destination directory")))
        self.captureButton.setText(kdecore.i18n(_fromUtf8("Capture")))

from PyKDE4.kio import KUrlRequester
from PyKDE4.kdeui import KPushButton, KIntNumInput
